SUPABASE_URL = "https://ikudnxtqwzsjzhzampqd.supabase.co"
SUPABASE_KEY = "sb_publishable_ddILdy2R1os5-fdk__IuBA_bNMD4yhP"
SUPABASE_SECRET_KEY = "sb_secret_37gyn85CNbKriiMVUwx7aw_6C9fl3oH"
SUPABASE_JWKS_URL = "https://ikudnxtqwzsjzhzampqd.supabase.co/auth/v1/.well-known/jwks.json"
# APIs de Deportes
API_FOOTBALL_KEY = "4c214a028f5001a3aec7273dcf178f74"

# APIs de IA y Pagos
GOOGLE_STUDIO_KEY = "AIzaSyBFrMpt-VIVid-dz-p4waygIBV8U6iDbfA"
GOOGLE_API_KEY = "AQ.Ab8RN6LoYmaUz7aXW9d4pv5mXHAp3qofRwX9GDS-95ACQpIFzg"

# Configuración opcional
LOG_LEVEL = "info"
DEBUG_MODE = false
